name: ticketron
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_snake_navigationbar: ^0.6.1
  flutter_animate: ^4.5.0
  cached_network_image: ^3.3.1
  intl: ^0.17.0
  mobile_scanner: ^5.1.1
  get: ^4.6.6
  permission_handler: ^11.0.1
  firebase_core: ^2.9.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.4.0
  firebase_storage: ^11.2.4
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.2.1+1
  firebase_messaging: ^14.9.4
  http: ^1.2.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  assets:
    - icons/
    - images/

  uses-material-design: true