name: ticketron
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_snake_navigationbar: ^0.6.1
  flutter_animate: ^4.5.0
  cached_network_image: ^3.3.1
  mobile_scanner: ^5.1.1
  get: ^4.6.6
  permission_handler: ^11.0.1
  firebase_core: ^2.9.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.4.0
  firebase_storage: ^11.2.4
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.7.0
  flutter_local_notifications: ^17.2.1+1
  firebase_messaging: ^14.9.4
  http: ^1.2.1
  image_picker: ^1.1.2
  flutterwave_standard: ^1.0.8
  # zego_uikit_prebuilt_live_streaming: ^3.11.0
  shimmer: ^2.0.0
  skeleton_loader: ^2.0.0+4
  share_plus: ^6.3.0
  path_provider: ^2.1.3
  image_gallery_saver: ^2.0.3
  intl: ^0.19.0
  url_launcher: ^6.3.0
  location: ^7.0.0
  flutter_polyline_points: ^2.1.0
  uuid: ^4.4.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"
  min_sdk_android: 19


flutter:
  assets:
    - icons/
    - images/

  uses-material-design: true