// import 'dart:math';

// import 'package:ticketron/models/event_model.dart';
// import 'package:ticketron/models/ticket_model.dart';
// import 'package:ticketron/models/user_model.dart';

// // Generate a random avatar URL
// String getRandomAvatar() {
//   List<String> avatars = [
//     "https://randomuser.me/api/portraits/men/1.jpg",
//     "https://randomuser.me/api/portraits/women/1.jpg",
//     "https://randomuser.me/api/portraits/men/2.jpg",
//     "https://randomuser.me/api/portraits/women/2.jpg",
//     "https://randomuser.me/api/portraits/men/3.jpg",
//     "https://randomuser.me/api/portraits/women/3.jpg",
//   ];
//   return avatars[Random().nextInt(avatars.length)];
// }





// // Dummy data for events and tickets
// List<Event> events = [
//   Event(
//     id: 1,
//     title: "Tech Conference 2024",
//     date: DateTime(2024, 7, 20),
//     time: "10:00 AM - 5:00 PM",
//     location: "Tech Expo Center",
//     price: Price(premiumPrice: 150.0, regularPrice: 50.0),
//     description: "A conference bringing together tech enthusiasts and professionals.",
//     organizer: Organizer(
//       name: "TechEvents Inc.",
//       verified: true,
//       logoUrl: "https://events.ats.co.za/images/event3.jpg",
//       category: "Technology",
//     ),
//     agenda: [
//       AgendaItem(
//         title: "Opening Keynote",
//         speaker: "John Doe",
//         startTime: "10:00 AM",
//         endTime: "11:00 AM",
//         speakerImageUrl: getRandomAvatar(),
//       ),
//       AgendaItem(
//         title: "AI in 2024",
//         speaker: "Jane Smith",
//         startTime: "11:30 AM",
//         endTime: "12:30 PM",
//         speakerImageUrl: getRandomAvatar(),
//       ),
//     ],
//     images: [
//       Image(url: "https://cdn.pixabay.com/video/2022/06/14/120281-720504960_tiny.jpg"),
//       Image(url: "https://static.vecteezy.com/system/resources/previews/002/710/027/original/fluid-gradient-background-vector.jpg"),
//     ],
//     videoUrl: "https://www.youtube.com/watch?v=example",
//     ticketsLeft: 100,
//     category: "Conference",
//     locationMapUrl: "https://maps.google.com/?q=Tech+Expo+Center",
//   ),
//   Event(
//     id: 2,
//     title: "Art Expo 2024",
//     date: DateTime(2024, 8, 15),
//     time: "9:00 AM - 6:00 PM",
//     location: "Art Gallery Hall",
//     price: Price(premiumPrice: 100.0, regularPrice: 20.0),
//     description: "Explore the latest in modern art.",
//     organizer: Organizer(
//       name: "ArtWorld",
//       verified: true,
//       logoUrl: "https://content.jdmagicbox.com/comp/ernakulam/m4/0484px484.x484.140206113128.a9m4/catalogue/we-create-events-panampilly-nagar-ernakulam-event-management-companies-nsobpzm660.jpg",
//       category: "Art",
//     ),
//     agenda: [
//       AgendaItem(
//         title: "Modern Art Trends",
//         speaker: "Alice Johnson",
//         startTime: "9:30 AM",
//         endTime: "10:30 AM",
//         speakerImageUrl: getRandomAvatar(),
//       ),
//       AgendaItem(
//         title: "Interactive Art Workshop",
//         speaker: "Robert Brown",
//         startTime: "11:00 AM",
//         endTime: "1:00 PM",
//         speakerImageUrl: getRandomAvatar(),
//       ),
//     ],
//     images: [
//       Image(url: "https://4kwallpapers.com/images/wallpapers/fluidic-glossy-gradient-background-purple-background-3440x1440-7641.jpg"),
//       Image(url: "https://events.ats.co.za/images/event3.jpg"),
//     ],
//     videoUrl: "https://www.youtube.com/watch?v=example",
//     ticketsLeft: 50,
//     category: "Exhibition",
//     locationMapUrl: "https://maps.google.com/?q=Art+Gallery+Hall",
//   ),
//   Event(
//     id: 3,
//     title: "Music Festival 2024",
//     date: DateTime(2024, 9, 10),
//     time: "2:00 PM - 11:00 PM",
//     location: "Open Air Stadium",
//     price: Price(premiumPrice: 200.0, regularPrice: 80.0),
//     description: "Join us for a day of live music and entertainment.",
//     organizer: Organizer(
//       name: "LiveNation",
//       verified: true,
//       logoUrl: "https://www.eventsindustryforum.co.uk/images/articles/about_the_eif.jpg",
//       category: "Music",
//     ),
//     agenda: [
//       AgendaItem(
//         title: "Opening Act",
//         speaker: "Band A",
//         startTime: "2:00 PM",
//         endTime: "3:00 PM",
//         speakerImageUrl: getRandomAvatar(),
//       ),
//       AgendaItem(
//         title: "Headline Performance",
//         speaker: "Artist B",
//         startTime: "8:00 PM",
//         endTime: "10:00 PM",
//         speakerImageUrl: getRandomAvatar(),
//       ),
//     ],
//     images: [
//       Image(url: "https://cdn.pixabay.com/video/2022/06/14/120281-720504960_tiny.jpg"),
//       Image(url: "https://static.vecteezy.com/system/resources/previews/002/710/027/original/fluid-gradient-background-vector.jpg"),
//     ],
//     videoUrl: "https://www.youtube.com/watch?v=example",
//     ticketsLeft: 200,
//     category: "Festival",
//     locationMapUrl: "https://maps.google.com/?q=Open+Air+Stadium",
//   ),
//   Event(
//     id: 4,
//     title: "Startup Pitch Night",
//     date: DateTime(2024, 10, 5),
//     time: "6:00 PM - 9:00 PM",
//     location: "Innovation Hub",
//     price: Price(premiumPrice: 50.0, regularPrice: 10.0),
//     description: "Pitch your startup ideas to investors and industry experts.",
//     organizer: Organizer(
//       name: "Startup Inc.",
//       verified: true,
//       logoUrl: "https://content.jdmagicbox.com/comp/ernakulam/m4/0484px484.x484.140206113128.a9m4/catalogue/we-create-events-panampilly-nagar-ernakulam-event-management-companies-nsobpzm660.jpg",
//       category: "Business",
//     ),
//     agenda: [
//       AgendaItem(
//         title: "Introduction",
//         speaker: "CEO Startup Inc.",
//         startTime: "6:00 PM",
//         endTime: "6:30 PM",
//         speakerImageUrl: getRandomAvatar(),
//       ),
//       AgendaItem(
//         title: "Pitch Session",
//         speaker: "Various Startups",
//         startTime: "6:30 PM",
//         endTime: "8:30 PM",
//         speakerImageUrl: getRandomAvatar(),
//       ),
//     ],
//     images: [
//       Image(url: "https://events.ats.co.za/images/event3.jpg"),
//       Image(url: "https://4kwallpapers.com/images/wallpapers/fluidic-glossy-gradient-background-purple-background-3440x1440-7641.jpg"),
//     ],
//     videoUrl: "https://www.youtube.com/watch?v=example",
//     ticketsLeft: 75,
//     category: "Business",
//     locationMapUrl: "https://maps.google.com/?q=Innovation+Hub",
//   ),
//   Event(
//     id: 5,
//     title: "Health and Wellness Fair",
//     date: DateTime(2024, 11, 20),
//     time: "10:00 AM - 4:00 PM",
//     location: "Community Center",
//     price: Price(premiumPrice: 30.0, regularPrice: 0.0),
//     description: "Learn about health and wellness from experts.",
//     organizer: Organizer(
//       name: "HealthFirst",
//       verified: true,
//       logoUrl: "https://www.eventsindustryforum.co.uk/images/articles/about_the_eif.jpg",
//       category: "Health",
//     ),
//     agenda: [
//       AgendaItem(
//         title: "Morning Yoga",
//         speaker: "Yoga Instructor",
//         startTime: "10:00 AM",
//         endTime: "11:00 AM",
//         speakerImageUrl: getRandomAvatar(),
//       ),
//       AgendaItem(
//         title: "Healthy Eating Seminar",
//         speaker: "Nutritionist",
//         startTime: "12:00 PM",
//         endTime: "1:00 PM",
//         speakerImageUrl: getRandomAvatar(),
//       ),
//     ],
//     images: [
//       Image(url: "https://static.vecteezy.com/system/resources/previews/002/710/027/original/fluid-gradient-background-vector.jpg"),
//       Image(url: "https://4kwallpapers.com/images/wallpapers/fluidic-glossy-gradient-background-purple-background-3440x1440-7641.jpg"),
//     ],
//     videoUrl: "https://www.youtube.com/watch?v=example",
//     ticketsLeft: 150,
//     category: "Health",
//     locationMapUrl: "https://maps.google.com/?q=Community+Center",
//   ),
// ];



// List<Ticket> tickets = [
//   Ticket(
//     id: "TICKET001",
//     eventId: 1,
//     user: UserModel(
//       userId: "USER001",
//       name: "Michael Scott",
//       email: "michael.scott@example.com",
//       avatarUrl: getRandomAvatar(),
//     ),
//     seat: "A10",
//     ticketType: "Premium",
//     quantity: 1,
//     totalPrice: 150.0,
//     status: "Upcoming",
//     barcode: "BARCODE001",
//     qrcode: "QRCODE001",
//   ),
//   Ticket(
//     id: "TICKET002",
//     eventId: 2,
//     user: UserModel(
//       userId: "USER002",
//       name: "Pam Beesly",
//       email: "pam.beesly@example.com",
//       avatarUrl: getRandomAvatar(),
//     ),
//     seat: "B15",
//     ticketType: "Regular",
//     quantity: 2,
//     totalPrice: 40.0,
//     status: "Upcoming",
//     barcode: "BARCODE002",
//     qrcode: "QRCODE002",
//   ),
//   Ticket(
//     id: "TICKET003",
//     eventId: 3,
//     user: UserModel(
//       userId: "USER003",
//       name: "Jim Halpert",
//       email: "jim.halpert@example.com",
//       avatarUrl: getRandomAvatar(),
//     ),
//     seat: "C12",
//     ticketType: "Premium",
//     quantity: 2,
//     totalPrice: 400.0,
//     status: "Upcoming",
//     barcode: "BARCODE003",
//     qrcode: "QRCODE003",
//   ),
//   Ticket(
//     id: "TICKET004",
//     eventId: 4,
//     user: UserModel(
//       userId: "USER004",
//       name: "Dwight Schrute",
//       email: "dwight.schrute@example.com",
//       avatarUrl: getRandomAvatar(),
//     ),
//     seat: "D3",
//     ticketType: "Regular",
//     quantity: 1,
//     totalPrice: 10.0,
//     status: "Upcoming",
//     barcode: "BARCODE004",
//     qrcode: "QRCODE004",
//   ),
//   Ticket(
//     id: "TICKET005",
//     eventId: 5,
//     user: UserModel(
//       userId: "USER005",
//       name: "Angela Martin",
//       email: "angela.martin@example.com",
//       avatarUrl: getRandomAvatar(),
//     ),
//     seat: "E9",
//     ticketType: "Regular",
//     quantity: 3,
//     totalPrice: 0.0,
//     status: "Upcoming",
//     barcode: "BARCODE005",
//     qrcode: "QRCODE005",
//   ),
//   Ticket(
//     id: "TICKET006",
//     eventId: 2,
//     user: UserModel(
//       userId: "USER006",
//       name: "Ryan Howard",
//       email: "ryan.howard@example.com",
//       avatarUrl: getRandomAvatar(),
//     ),
//     seat: "F4",
//     ticketType: "Premium",
//     quantity: 1,
//     totalPrice: 100.0,
//     status: "Past",
//     barcode: "BARCODE006",
//     qrcode: "QRCODE006",
//   ),
//   Ticket(
//     id: "TICKET007",
//     eventId: 1,
//     user: UserModel(
//       userId: "USER007",
//       name: "Kelly Kapoor",
//       email: "kelly.kapoor@example.com",
//       avatarUrl: getRandomAvatar(),
//     ),
//     seat: "G8",
//     ticketType: "Regular",
//     quantity: 2,
//     totalPrice: 30.0,
//     status: "Past",
//     barcode: "BARCODE007",
//     qrcode: "QRCODE007",
//   ),
//   Ticket(
//     id: "TICKET008",
//     eventId: 3,
//     user: UserModel(
//       userId: "USER008",
//       name: "Stanley Hudson",
//       email: "stanley.hudson@example.com",
//       avatarUrl: getRandomAvatar(),
//     ),
//     seat: "H5",
//     ticketType: "Premium",
//     quantity: 1,
//     totalPrice: 200.0,
//     status: "Past",
//     barcode: "BARCODE008",
//     qrcode: "QRCODE008",
//   ),
//   Ticket(
//     id: "TICKET009",
//     eventId: 3,
//     user: UserModel(
//       userId: "USER009",
//       name: "Kevin Malone",
//       email: "kevin.malone@example.com",
//       avatarUrl: getRandomAvatar(),
//     ),
//     seat: "I2",
//     ticketType: "Regular",
//     quantity: 1,
//     totalPrice: 20.0,
//     status: "Past",
//     barcode: "BARCODE009",
//     qrcode: "QRCODE009",
//   ),
//   Ticket(
//     id: "TICKET010",
//     eventId: 1,
//     user: UserModel(
//       userId: "USER010",
//       name: "Toby Flenderson",
//       email: "toby.flenderson@example.com",
//       avatarUrl: getRandomAvatar(),
//     ),
//     seat: "J1",
//     ticketType: "Regular",
//     quantity: 2,
//     totalPrice: 0.0,
//     status: "Past",
//     barcode: "BARCODE010",
//     qrcode: "QRCODE010",
//   ),
// ];
